manifest:
  remotes:
    - name: lazerwalker
      url-base: https://github.com/lazerwalker
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: plover-hid-hog-attempt
      import: app/west.yml
  self:
    path: config
